#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55
# By considering the terms in the Fibonacci sequence whose values do not exceed four million
# find the sum of the even-valued terms.

def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)

sum = n = 0
while fib(n) < 4000000:
    if fib(n) & 1:
        sum += fib(n)

    n+=1

print(sum)